### PR TITLE
Fix loadFromDirectory error

### PR DESCRIPTION
**Pull request by adrienbrault**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Okay, nobody uses this feature and there are no tests for it, sorry about that ;) Have you seen this working?

**Comment by adrienbrault** [comment]
This was required to get https://github.com/matthiasnoback/behat-remote-code-coverage-extension to work ... and it does now 🎉

**Comment by matthiasnoback** [comment]
Well, okay then!

**Comment by matthiasnoback** [comment]
Released as v1.5.1

**Pull request merged**
