### PR TITLE
Adding Support for PHPUnit v9.0

### PR DESCRIPTION
**Pull request by ktamas77**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks!

**Comment by matthiasnoback** [comment]
Somehow the Travis build didn't run  for this PR. Once merged and released the build was broken. This library simply doesn't work yet with PHPUnit 9. If you have time to look into it, please do so. For me it would not be a problem if the PHPUnit 9 support would mean we release a new major version. So if you'd like to drop support for older PHPUnit versions, that's fine by me.

**Comment by ktamas77** [comment]
@matthiasnoback you right - PHPUnit 9's interface is fundamentally different, I had to refactor the code to match it properly. In order to do so, I also had to increase the minimum PHP requirement to PHP 7.3 as it's the minimum requirement for PHPUnit 9. And since it requires PHP 7.3, i dropped support for older PHP Versions. https://github.com/matthiasnoback/live-code-coverage/pull/14/

**Comment by matthiasnoback** [comment]
Wow that was fast! I'll take a look at it asap which might be in a few days.

Op vr 27 mrt. 2020 21:13 schreef Tamas Kalman <notifications@github.com>:

**Pull request merged**
